#!/bin/bash
set -euo pipefail

# prepare bin packages in dist
# expects python with installed dependencies
# required param: version

pyinstaller --collect-data grapheme --onefile test.py --name test-windows
pyinstaller --onefile test_no_click.py --name test-no-click-windows
