name: Build Binaries

on:
  push:
    branches:
      - '**'
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:

  build_linux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dev dependencies
      run: |
        pip install -e .

    - name: Build Release Executables
      run: |
        scripts/build_bin_linux 

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        if-no-files-found: error
        path: |
          dist/test*

  build_macos:
    runs-on: macos-11
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dev dependencies
      run: |
        pip install -e .

    - name: Build Release Executables
      run: |
        scripts/build_bin_macos

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        if-no-files-found: error
        path: |
          dist/test*

  build_windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dev dependencies
      run: |
        pip install -e .

    - name: Build Release Executables
      run: |
        scripts/build_bin_windows

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        if-no-files-found: error
        path: |
          dist/test*
